version: '3.7'

networks:
  usman-network:
    driver: bridge
    name: usman-network

services:

  php:
    build:
      context: ./docker/php-fpm

  nginx:
    build:
      context: ./docker/nginx        

  database:    
    build:
      context: ./docker/database  